### ISSUE TITLE
Development build fails

### ISSUE THREAD

**Issue by v-r0** [QuState/spinoza#2]
Compiling spinoza v0.1.0 (/Users/ds/Code/spinoza/spinoza)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> spinoza/src/lib.rs:8:12
  |
8 | #![feature(slice_swap_unchecked)]
  |            ^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> spinoza/src/lib.rs:9:12
  |
9 | #![feature(core_intrinsics)]
  |            ^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `spinoza` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...

**Comment by smu160** [comment]
Hi @v-r0,

The README was updated to include instructions on installing the nightly compiler and using it to build Spinoza. 

Thank you!
