### ISSUE TITLE
cargo build fails (linking with `cc` failed)

### ISSUE THREAD

**Issue by v-r0** [QuState/spinoza#3]
error: linking with `cc` failed: exit status: 1
= note: Undefined symbols for architecture x86_64

Solution proposed [here](https://stackoverflow.com/questions/28124221/error-linking-with-cc-failed-exit-code-1):
add the following to .cargo/config.toml or .cargo/config (either is fine)
```
[target.x86_64-apple-darwin]
rustflags = [
"-C", "link-arg=-undefined",
"-C", "link-arg=dynamic_lookup",
]
```
resolved the issue.

**Comment by smu160** [comment]
Will update the README for macOS users
